language: cpp
matrix:
  include:
  - os: linux
    env: NAME="flatpak build"
    sudo: required
    dist: trusty
    services: docker
    cache: ccache
    before_deploy:
    - openssl aes-256-cbc -K $encrypted_b892d17adcdd_key -iv $encrypted_b892d17adcdd_iv -in .travis/linux-flatpak/citra-sftp-flatpak.enc -out /tmp/citra-sftp-flatpak -d
    install: "./.travis/linux-flatpak/deps.sh"
    script: "./.travis/linux-flatpak/build.sh"
