language: cpp
matrix:
  include:
  - os: linux
    env: NAME="flatpak build"
    sudo: required
    dist: trusty
    services: docker
    cache: ccache
    install: "./.travis/linux-flatpak/deps.sh"
    script: "./.travis/linux-flatpak/build.sh"
    after_success: "./.travis/linux-flatpak/upload.sh"
